# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff587e1d2014ec155469efe01cc9d1d543f59585a9ce783a3a19d955e2eebd78032a7b01291abf073f066fe289dfd96dde267def874dbe68184a15301bc43b68

test:
  secret_key_base: fcd2e1f4f5324c34374400646017e3283396c7620e648c3579bb04d2d9eb7204fdc30bdde1514f58377a197e81ecc8dbe351794c764e0b464fbdf3edec84b782

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
